### ISSUE TITLE
Redirect elections.thelensnola.org to permanent race URL on election night

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#298]
That URL will stay as an index page. Instead, use the full, unique URL before, during and after election night so that it will be permanent and only ever have one location.

By swapping in new apps at the same URL, we were creating problems with SEO and social media sharing, really only for the sake of a nice URL and because we didn't have an archive of apps to consider.

This will also stop us from having to update iframe URLs after election night and it will no longer render social media and blogs posts' links broken after election night.

**Comment by myersnews** [comment]
Yeah I wondered about that approach.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Nov 19, 2015, at 4:53 PM, Thomas Thoren <notifications@github.com> wrote:

That URL will stay as an index page. Instead, use the full, unique URL
before, during and after election night so that it will be permanent and
only ever have one location.

By swapping in new apps at the same URL, we were creating problems with SEO
and social media sharing, really only for the sake of a nice URL and
because we didn't have an archive of apps to consider.

This will also stop us from having to update iframe URLs after election
night and it will no longer render social media and blogs posts' links
broken after election night.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/298>.

**Comment by myersnews** [comment]
We can still have a simple url- just redirect.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Nov 19, 2015, at 4:53 PM, Thomas Thoren <notifications@github.com> wrote:

That URL will stay as an index page. Instead, use the full, unique URL
before, during and after election night so that it will be permanent and
only ever have one location.

By swapping in new apps at the same URL, we were creating problems with SEO
and social media sharing, really only for the sake of a nice URL and
because we didn't have an archive of apps to consider.

This will also stop us from having to update iframe URLs after election
night and it will no longer render social media and blogs posts' links
broken after election night.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/298>.

**Comment by ThomasThoren** [comment]
That's probably the best bet.
