### ISSUE TITLE
"Last updated" text

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#330]
People won't know what 1:00 means. How about
Last updated XXX. Updated each minute. then the refresh circle.

**Comment by ThomasThoren** [comment]
Now that there is the countdown time and animation to show when an action will occur, we no longer need to worry about explaining the time interval.

This might make the "Last updated" language confusing though since we know the Secretary of State data won't update every 60 seconds. There will be times when the timer hits zero, it animates and yet the "Last updated" time won't change because the timestamp in the Secretary of State data is the same.

We could come up with better language, like "Current as of" or similar, but there would probably still be some confusion.

I don't know that we need the "Last updated/checked/results" language at all. We could remove it and only show the countdown timer. It's implied that you're being shown the latest results available, especially when we're showing you a timer that keeps resetting. Besides, who really cares when the Secretary of State hit publish on their results? Users will only care that they are seeing the latest results.

**Comment by myersnews** [comment]
Keep "last updated" and time, and countdown and don't worry if sos doesn't
update.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Mar 4, 2016, at 5:56 PM, Thomas Thoren <notifications@github.com> wrote:

Now that there is the countdown time and animation to show when an action
will occur, we no longer need to worry about explaining the time interval.

This might make the "Last updated" language confusing though since we know
the Secretary of State data won't update every 60 seconds. There will be
times when the timer hits zero, it animates and yet the "Last updated" time
won't change because the timestamp in the Secretary of State data is the
same.

We could come up with better language, like "Current as of" or similar, but
there would probably still be some confusion.

I don't know that we need the "Last updated/checked/results" language at
all. We could remove it and only show the countdown timer. It's implied
that you're being shown the latest results available, especially when we're
showing you a timer that keeps resetting. Besides, who really cares when
the Secretary of State hit publish on their results? Users will only care
that they are seeing the latest results.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/330#issuecomment-192528170>.

**Comment by myersnews** [comment]
countdown is 10 minutes

**Comment by ThomasThoren** [comment]
That's just for testing so it's out of the way. I'll switch it back now rather than later.
